services:
  - type: web
    name: misseli-backend
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: API_KEY_OPEN_AI
        sync: false
    healthCheckPath: /health
    autoDeploy: true
